# Generated by Django 3.1.7 on 2021-04-17 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_auto_20210418_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
